scripts/windows/Update_AD_Bridge.ps1

Check for the PS version, if 3 or more, we can use Invoke-WebRequest as
a download client, otherwise use WebClient on PS 2 or older

Fix AD upgrade to work on Windows server 2008

---

scripts/macos/remove_mac_agent.sh

The mac agent now contains an /opt/jc/bin/removeAgent script that will be versioned with the installed agent.  This change modifies the support script to first check for and run that script if it exists, otherwise perform the previous behavior.  This will allow the agent to add steps needed for uninstallation, without this support script needing to be modified and distributed on every change.

Shell out to agent remove script instead if it exists

---

scripts/macos/remove_mac_agent.sh

the recently added process check had an improper redirect to /dev/null, rendering it useless in actually killing processes left running after agent uninstall.

Fixed broken redirect in process check.

---

zero-touch/prestage_user_enrollment/CHANGELOG.md
zero-touch/prestage_user_enrollment/README.md
zero-touch/prestage_user_enrollment/jumpcloud_bootstrap_template.sh

Reverted changes from previous branch/ kept issue with time sync in other branch. 
Added variable for the short name of the welcome (first user) account to be deleted at the end of the flow. if the DELETE_ENROLLMENT_USERS bool is switched to false, the script will not delete the first users. It could be useful for admins who opt to run through the prestage before distribution to the end user.

Sa 646 jw remove first enrollment accounts

---

zero-touch/prestage_user_enrollment/jumpcloud_bootstrap_template.sh

System Context API call will fail for systems with skewed time. Proposed change to compare the system time with a NTP server. If the system clock is out of sync, the sntp command will set the clock to the correct time based on the provided NTP server.

Sa 646 jw update time before syscontextapi

---

zero-touch/prestage_user_enrollment/user_configuration_modules/active_user_no_password_update_company_email_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_or_active_user_company_email_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_or_active_user_last_name_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_user_company_email.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_user_personal_email.sh

All of the existing modules still had that \\n syntax during the workflow, those have been swapped to the "\n" newline syntax to prevent unintended slashes from displaying. 
The new module allows an existing jumpcloud user to activate using their company email and "Employee ID" secret word. No password prompt is displayed after the user is identified.

Sa 702 jw activated user configuration module

---

scripts/macos/RenameMacUserNameAndHomeDirectory.sh

The Rename Mac Username and Home Directory script should produce a log to verify that the script produced the desired result. 
The rename script will now:
Create a "JC_RENAME.log file" in the same directory as the rename script
Each error is logged and appended to the JC_RENAME.log file
A successful run of the rename script is logged to the JC_RENAME.log file

Sa 706 jc mac rename better logging

---

scripts/macos/RenameMacUserNameAndHomeDirectory.sh

Add two checks to the macOS rename script:
1) Add a check to see if Terminal has been granted full disk access. Abort if Terminal does not have full disk access.
2) Add a check to see if the account to be renamed differs from the home directory. If the home directory account name differs from the username to be renamed, the script will abort.

add check for username and different named home accounts

---

zero-touch/prestage_user_enrollment/automation scripts/generate_employeeIDs.ps1

Those wishing to use a user configuration module which requires a secret word may want to auto generate their employee ids to avoid manually entering data into the employee id field. This script provides admins with a simple way to automate the process. This PowerShell example takes the first two letters of the first name & last name and appends 4 random digits to the text string - forming a unique employee ID.

auto generate user's employeeID based on user name

---

zero-touch/prestage_user_enrollment/CHANGELOG.md
zero-touch/prestage_user_enrollment/jumpcloud_bootstrap_template.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_or_active_user_company_email_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_or_active_user_last_name_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_or_active_user_personal_email_and_secret.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_user_company_email.sh
zero-touch/prestage_user_enrollment/user_configuration_modules/pending_user_personal_email.sh

Fix for the remnant files which are left over if dscl is used to delete the enrollment user and the decrypt user. The use of Sysadminctl -deleteuser has a few additional checks built in to ensure the last SecureToken user on a system is not removed. The script now waits until no users are logged in or if the enrollment user is not logged in before processing the delete users block of code. 
This user deletion block of code was moved to the last gate check in the script. Admins who wish to restart their systems as part of the process can do so at the end of the last gate. Deleting users with sysadminctl is a more elegant way of removing users in 10.13+ and seems to resolve some of the delay at first user login.
The script is now caffeinated to account for enrollment users who walk away …

Sa 736 jw delay welcome user files deletion

---

scripts/api/v1/radius/dhcpRadiusUpdate.sh

The script does not need to depend on *both* `curl` and `wget`. Not only is this redundant, but this also allows the script to be run from an EdgeRouter (i.e., vanilla EdgeOS) without installing any additional packages. Not going to lie, this is the primary motivation for this PR :).
Also, `wget` is arguably less common in OOTB/vanilla installs of Linux distros as compared to `curl`, which is _nearly_ guaranteed (except for the tiniest distros).
Tangentially, this also removes some trailing whitespace.

Remove dependency on `wget`

---

scripts/windows/FixWindowsAgent.ps1
scripts/windows/InstallWindowsAgent.ps1

Adds flush dns prior to install to account for cases where infrastructure changes occur and windows DNS cache keeps old address leading to failed installed agent.

Add_Flush_DNS_Cache

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Available Updates

Short command to install and reboot macOS computers with pending updates. The command should be run  as root, and a timeout of 30mins should be set to account for slow networks and large downloads. I will update the import URL after merge to master.

install available updates command

---

scripts/macos/install_agent_and_serviceaccount.sh

In order to keep people from having a bad time with their install I'd like to require the connect key to be present and check if the user is a Secure Token admin unless they use the `-s` parameter for silent (connect key still required)

update to use silent flag, require connect key, do username checking

---

scripts/windows/InstallWindowsAgent.ps1

Had an issue where the client install wasn't working saying the vcredist_x86.exe file was corrupted.
Browsing the file directly revealed the issue with Sonicwall blocking the download.

Fix SonicwWall firewalls blocking vcredist_x86.exe download

---

scripts/macos/RenameMacUserNameAndHomeDirectory.sh

Account name search should match the whole word for the account being changed, this should prevent accounts with similar names from appearing to be logged in.

grep only account name whole word match

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Cache Latest MacOS Installer.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Latest MacOS Installer.md

Two Commands:
Mac - Cache Latest MacOS Installer | v1.0 JCCG
This command is used to cache Major OS installers, the softwareupdate command in MacOS Catalina includes the --fetch-full-installer command which will allow admins to remotely cache full OS installers on remote Catalina systems. This command will add systems to a system group to help determine which systems have cached the last OS.
Mac - Install Latest MacOS Installer | v1.0 JCCG
This command will install a full OS installer on remote macos systems. If the specified macOS installer exists on a system the command will run the installer and remove the system from the specified system group in the cache latest os installer command.

Sa 951 jw update major os

---

scripts/macos/install_agent_and_serviceaccount.sh

Syntax changes to account for the case where passwords contain spaces, other shellcheck syntax fixes for variable substitution. Added invalid case parameter.

syntax and shellcheck fixes for complex passwords

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install Microsoft Office.md

This change includes a sample script to install Microsoft Office for Microsoft 365 users on Mac OS.
The script is based on the sample DMG install script.

Sample script to install Microsoft Office on Mac OS

---

MDM/Custom Configuration Profiles/profiles/JumpCloud-Agent & Bash.mobileconfig
MDM/Custom Configuration Profiles/readme.md

PPPC profile example for jumpcloud-agent and bash where additional PPPC permissions may be necessary.

Sa 1411 jcagent pppc

---

scripts/macos/install_agent_and_serviceaccount.sh

Updated the MacOS agent install script to support Big Sur, which is 11.0.

Update agent install script to support MacOS Big Sur

---

scripts/macos/install_agent_and_serviceaccount.sh

This PR updates the `install_agent_and_serviceaccount.sh` script to install Rosetta2 on Macs with M1 (Apple Silicon) chips, if it has not already been installed.  This is required to allow the JumpCloud agent to run on M1 Macs until we can release Universal packages with native M1 support.
The changes also include silencing `shellcheck` warnings.
This script has been tested on Mac Developer Transition Kits (Mac Mini's with M1 chips), both with and without Rosetta2 already installed.

HE-1376 Install Rosetta2 on M1 Macs

---

scripts/macos/install_agent_and_serviceaccount.sh

Add an exit condition to account for scenarios where the installer throws an error.
If installer -pkg /tmp/jumpcloud-agent.pkg -target / returns 1, exit the script with exit code 1, else continue and exit 0

exit 1 on failed agent install

---

PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Prompt Expiring Users To Update Password.md
PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Prompt Users To Update Password With Expiration Date Logic.md
PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Prompt Users To Update Password.md

This adds new logging to the 3 Password Expiration Prompt Scripts to catch warnings and better report expected outcomes from the following scenarios to the JumpCloud Admin Console Command Results log output:
1. No active users found on the system
2. No active JumpCloud users found on the system
3. Invalid `state` for any found JumpCloud user other than `Active` (this assists non English OS versions)
4. Any Active JumpCloud users found but without their passwords expiring.
And for the 2 scripts that validate user password expiry as part of the logic to prompt for password reset, we're also outputting:
1. When the Active JumpCloud user has their password set to never expire.

SJ-2472 Update Logging for Password Expiration Prompt Scripts

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Verify JumpCloud Service Account.md

Add loop to output users with secure token to the check for secure token script. It would be useful to know what users have secure token if the JumpCloud Service account is not on the system.

output users w/ securetoken

---

PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Get Windows Cached Credentials.md

Publishes Windows command to the command gallery to output cached credentials on a system to help with troubleshooting lockouts etc.

SA-1861 - Windows Cached Credentials Command

---

.github/pull_request_template.md
.gitignore
PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Agent and Service Account.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Verify JumpCloud Service Account.md
scripts/macos/verify_serviceaccount.sh

* [SA-1989](https://jumpcloud.atlassian.net/browse/SA-1898) - Support GH mac scripts do not support Big Sur
Several older scripts written before Big Sur contained MacOS minor version statements which would exclude Big Sur. Those scripts were updated to only exit if the MacOS version was prior to 10.13. 
Added a pull request template and a .gitignore file to exclude some files
N/A

Sa 1898 update 10.13 scripts

---

PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Disable Local User.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Disable Local User.md
PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Disable Local User.md

* [SA-1939](https://jumpcloud.atlassian.net/browse/SA-1939) - Disable Local Users Scripts
Scripts to disable & logoff local users by username.
Not particularly tricky but usernames are disabled by a regex match pattern. If multiple users match the pattern it's best to run the script with the disable variable set off to see which users would be disabled first. 
Add a local user to a system, import the command, test that the user can me disabled by running the commands, and that the user is kicked off the system.

Sa 1939 disable local users scripts

---

scripts/linux/agent_diagnostics.sh
scripts/macos/agent_diagnostics.sh

* [HE-1710](https://jumpcloud.atlassian.net/browse/HE-1710) - Diagnostic scripts should gather all relevant agent logs
Ensures the `agent_dignostics.sh` scripts gather all relevant agent logs.
No.
Execute the appropriate diagnostic script on a JC-managed system (MacOS or Linux). Ensure that all `/var/log/jc*` log files are added to the resulting archive. On MacOS, the archive should include `/var/log/jumpcloud-loginwindow/*`.

HE-1710 Update agent_diagnostics scripts

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Agent and Service Account.md
scripts/macos/install_agent_and_serviceaccount.sh

* [HE-1791](https://jumpcloud.atlassian.net/browse/HE-1791) - Fail agent install with no ST
The agent installer now supports a special value (=skip) in the JumpCloud-SecureToken-Creds.txt file and service account creation will be skipped rather than tried and failed.
No.
- Running the `install_agent_and_serviceaccount.sh` script with the `-s` option.
- Using the powershell module `Mac - Install Agent and Service Account` with the `-s` option.

HE-1791 More gracefully handle skipping creating the service account

---

scripts/automation/updateManagedAppleId.ps1

* [<SA-2268>](https://jumpcloud.atlassian.net/browse/SA-2268) - Custom script to add ManagedAppleID 
There is no UI element to add the ManagedAppleID field to a user in JumpCloud. This script should help admins, generate a template to set this field.
In the next PowerShell SDK release we'll include the field to set and get the current ManagedAppleID for users in an org. This script will have to be updated at that point in time. 
Pull the script, generate the file, update a few users with a Managed Apple ID field

Sa 2268 managed apple id assignment

---

.circleci/workflows.yml
scripts/macos/install_agent_and_serviceaccount.sh

* [HE-1935](https://jumpcloud.atlassian.net/browse/HE-1935) - Update Installer Script for macOS
When installing the agent on Monterey, the user is warned about needed to give the agent FDA and asks to confirm this unless the `-f` flag is passed in.
No.
Run the install script with and without the `-f` option and on Monterey and an older macOS version.
* Monterey
* with `-f`: a message about FDA is printed but no user confirmation is asked for
* without `-f`: a message about FDA is printed and user must confirm `y` or `n`
* Any older macOS version: no FDA message is printed

HE-1935 Add messaging and user confirmation for macOS full disk access

---

.circleci/workflows.yml
PowerShell/Deploy/Build-Module.ps1
PowerShell/Deploy/SdkSync/jcapiToSupportSync.ps1
PowerShell/Deploy/Setup-Dependencies.ps1
PowerShell/JumpCloud Module/Docs/JumpCloud.md
PowerShell/JumpCloud Module/JumpCloud.psd1
PowerShell/JumpCloud Module/Public/Authentication/Update-JCModule.ps1
PowerShell/ModuleBanner.md
PowerShell/ModuleChangelog.md

* [SA-2284](https://jumpcloud.atlassian.net/browse/SA-2284) - Revert changes to Update-JCModule
Reverts changes made to the Update-JCModule function to add CodeArtifact repository support. 
No this is a reversion, this worked previously
Update 1.18.8 -1.18.11 should work without issue regardless of PowerShellGet version. 
Update 1.18.8 -1.18.11 should work without issue regardless of PowerShellGet version & SDK Version

revert Update-JCModule

---

PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Run As Signed In User Template.md

The `%Command` declaration and `invoke-ascurrentuser` statement don’t need to be inside an `else` block. The way it is now…if the `if` condition is true (i.e. the module is not installed)…all the command does is install the module before it exits. You’d have to run the command twice.
Also, some customers are confused by the fact that any command executed using `invoke-ascurrentuser` returns the PID (and not the stdout) of the spawned process. I added a note clarifying this issue, and provided an example of how to retrieve `stdout` if so desired.
You may receive the following error if testing on a VM:
```bash
install-module : NuGet provider is required to interact with NuGet-based repositories.
Please ensure that '2.8.5.201' or newer version of NuGet provider is installed.
```
I added a …

Update template for RunAsUser module

---

scripts/windows/FixWindowsAgent.ps1
scripts/windows/InstallWindowsAgent.ps1

* [SA-2343](https://jumpcloud.atlassian.net/browse/SA-2343) - Switch Async calls to synchronous in fixWindowsAgent.ps1, InstallWindowsAgent.ps1
- Fixes the problem that current script exits with exit code 5 although it works well, so using it this way `powershell -command ./InstallWindowsAgent.ps1 -JumpCloudConnectKey "{{ jumpcloud_key }}"` in, e.g., ansible, will result in error
- Speeds up a bit, since it will not have 3 seconds waiting period
NA
Test both functions work and exit 0

Async to sync downloads fix/ install windows agent

---

.circleci/config.yml
.circleci/workflows.yml
PowerShell/JumpCloud Module/LICENSE
PowerShell/LICENSE

* [SA-2351](https://jumpcloud.atlassian.net/browse/SA-2351) - Fix Circle-CI Path-Filtering Mapping
Path filtering has never worked as intended. This updates a regex pattern to search the /support repository and only kick off the PowerShell Build Process if files in that repository have been changed. 
Commit a "test" file to any directory outside Support/PowerShell/ - the PS Pipeline should not build
Commit a "test" file to a directory like Support/PowerShell/JumpCloud Command Gallery - the PS Pipeline should not build. 
Commit a "test" file to the Support/PowerShell/PowerShell Module directory - the PS Pipeline should build.

Sa 2351 manual build check

---

scripts/automation/updateManagedAppleId.ps1

* [SA-2272](https://jumpcloud.atlassian.net/browse/SA-2272) - Update Managed Apple ID script when SDKs are released
Removes calling API manually and instead uses PowerShell SDKs
No
* Have old version of SDK.V1 installed - ensure that it gets updated
* Don't have SDK.V1 installed - ensure that it gets installed
* Ensure that rows are skipped if they meet the following criteria:
* Null/Whitespace, Invalid Email Address or ManagedAppleID already matches

Update Managed Apple ID script when SDKs are released

---

_posts/2022-02-10-Group-Systems-By-MDM-Status.md
tag/mdm.md

* [SA-2395](https://jumpcloud.atlassian.net/browse/SA-2395) - Group mac systems by MDM approval status
Gathering MDM approval status is tricky in the UI, maintaining system groups membership is impossible without the API. This script groups systems by the `system.mdm.userapproved` attribute. User Approved MDM is required for specific MDM workflows .
Two groups will be created while running this script: 
`MacOS-MDM-Approved`
`MacOS-MDM-Pending`
Mac systems are queried while running this script. If they have their user approval attribute set (and are managed by JumpCloud MDM) those systems are added to the `MacOS-MDM-Approved` group. Systems without this attribute are placed in the `MacOS-MDM-Pending` group. Membership is updated each time the script is run. 
No but systems enrolled in MDM …

MDM group example

---

assets/css/style.scss

* [SA-2419](https://jumpcloud.atlassian.net/browse/SA-2419) - Improve visibility on larger resolutions
Increases the size of the margins to allow for easier reading at larger resolutions
No
1. `cd` into the theme's directory
2. Install [jekyll](Install this: https://jekyllrb.com)
3. Run `deploy/bootstrap` to install the necessary dependencies
4. Run`bundle add webrick` (potentially already installed)
5. Run `bundle exec jekyll serve` to start the preview server
6. Visit [`localhost:4000`](http://localhost:4000) in your browser to preview the theme
7. Check various posts/pages at different resolutions
Before:
After:

SA-2419 - Increase .main-content max-width on larger resolutions

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Rename System HostName LocalHostName and ComputerName from JumpCloud.md

* [SA-2607](https://jumpcloud.atlassian.net/browse/SA-2607) - MacOS Rename Hostname script
Mostly customer confusion surrounding the [System Context API](https://support.jumpcloud.com/support/s/article/System-Context-API-KB-Information). The previous iteration of this script would only run on systems enrolled in JumpCloud with an admin connect key. Systems enrolled with MDM / User portal installation were ineligible to use the system context api. 
This script was updated to make use of the read only API Key. In addition, before setting the LocalHostName, the script will validate that the desired name matches the [bonjour requirements](https://apple.lib.utah.edu/bonjour-naming-guidelines/). Namely LocalHostName strings must be: 
* Be a maximum 63 characters in length
* Contain no …

update mac rename hostname script [skip ci]

---

PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Install Remote Assist.md

* [TX-397](https://jumpcloud.atlassian.net/browse/TX-397) - RAS EA Uninstall on Windows for Permission fix
Uninstall any versions of RAA in `C:\Program Files\JumpCloud` before installing the new version. Permissions on that folder are restrictive, and subsequent packages will be installed to a different location. The explicit uninstallation prevents having two versions installed simultaneously which could be most confusing.
The uninstaller path is hardcoded because the installed versions don't have support for PowerShell cmdlets such as `Uninstall-Package`
Run the command without RAA installed, and run the command with RAA installed

TX-397 - Uninstall legacy Remote Assist before installation

---

PowerShell/JumpCloud Module/Public/Utilities/Backup-JCOrganization.ps1
PowerShell/ModuleChangelog.md

* [SA-2670](https://jumpcloud.atlassian.net/browse/SA-2670) - Improved Error Reporting for Get-JCBackup
Backup-JCOrganization creates background jobs for each type of backup object requested. If there was a timeout, internet outage or other API error which prevented the job from gathering data from the JumpCloud API an error was not thrown. Now the tasks requested of each job are wrapped in a try/catch loop. Status of each job should be reported at the end of a backup job.
- Import the local module and connect to a JumpCloud organization.
- Ensure at least one user is bound to one system
Test that the function still works as expected
- Run `Backup-JCOrganization -Type Organizations, User -Path -Association ./ -debug`
- The Backup Jobs should complete without error
Test that the function …

Sa 2670 jc backup error reporting

---

scripts/macos/install_agent_and_serviceaccount.sh
scripts/windows/InstallWindowsAgent.ps1

* [HE-2491](https://jumpcloud.atlassian.net/browse/HE-2491) - Use CDN for new agent install for Windows/macOS command line
Changes the URL for the agent download to the new CDN path.
No
Test agent can be installed for macOS/Windows using the scripts.

HE-2491 - Use CDN for new agent install for Windows/macOS command line

---

scripts/macos/remove_mac_agent.sh

* [SA-3079](https://jumpcloud.atlassian.net/browse/SA-3079) - Uninstall Mac Agent Changes
This script change adds several checks to the `remove_mac_agent.sh` script. Per customer asks, when we remove the JumpCloud agent from a system we should also remove
- Remote Assist & JumpCloudServiceAccount Applications
- Launch Agents, Daemons
- opt/jc_user_ro directories
No, the script will check if any of the items listed above are present on the system before attempting to delete them from a system.
On a JumpCloud managed system, install the Remote Assist App & ensure at least one user is bound to the device. 
1. Run this modified `remove_mac_agent.sh` script: `sudo sh /path/to/remove_mac_agent.sh`
2. Validate that the JumpCloud agent was removed
3. Validate that the `opt/jc_user_ro` directory …

Sa 3079 uninstall script changes

---

.gitignore
scripts/automation/Radius/Functions/Private/Generate-UserCert.ps1
scripts/automation/Radius/Functions/Private/Get-CertInfo.ps1
scripts/automation/Radius/Functions/Private/Get-ExpiringCertInfo.ps1
scripts/automation/Radius/Functions/Private/Show-RadiusMainMenu.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1
scripts/automation/Radius/Functions/Public/Generate-UserCerts.ps1

* [SA-3171](https://jumpcloud.atlassian.net/browse/SA-3171) - Re-Issue Expiring User Certificates
This release enables admins to re-generate Radius user certificates and re-deploy them to systems without creating duplicate certificates. Generated user certificates in the `userCerts` directory are checked against their current expiration date. If local user certificates are set to expire within 15 days, the admin running the PowerShell automation will receive a notification that a number of certificates are due to expire soon. 
Admins can then go and regenerate user certificates to address the soon-to-expire certificates.
**User Certificate Expiration Notification**
- In `config.ps1` update the `$JCUSERCERTVALIDITY` variable to be 90 days
- Generate user certificates for a group of users. …

Sa 3171 replace expiring cert

---

scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1
scripts/automation/Radius/readme.md

* [SA-3199](https://jumpcloud.atlassian.net/browse/SA-3199) - macOS Specify SSID and associate user certificate
In the previous release, macOS end users were prompted no less than three times to set their radius certificate identity preference to the desired Radius Network, to allow eapolclient access to sign using the private key from the cert and finally allow eapolclient access to use the private key from the user cert.
This release eliminates unnecessary user interaction but automatically assigning the user certificate to the SSID of the radius network and giving `eapolclinet` access to the private key during certificate import.
Populate the `$NETWORKSSID` variable in `config.ps1`. Generate user certs and distribute to devices. When connecting to the Radius network specified in the …

SA-3199 Specify macOS SSID when importing user certificate

---

scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Private/Clear-JCQueuedCommand.ps1
scripts/automation/Radius/Functions/Private/Invoke-CommandRun.ps1

* [SA-3202](https://jumpcloud.atlassian.net/browse/SA-3202) - Add custom user agent on Radius Passwordless Generation scripts
User agent added to invoke rest method calls to distinguish calls from PowerShell module
Generate user certs/ distribute there should be no changes to the functionality of the project
[SA-3202]: https://jumpcloud.atlassian.net/browse/SA-3202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

userAgent on invoke rest method scripts

---

scripts/windows/FixWindowsAgent.ps1
scripts/windows/InstallWindowsAgent.ps1

* [SA-3208](https://jumpcloud.atlassian.net/browse/SA-3208) - SA-3208-Windows-Agent-Installer-MSI
Replace .exe installer to .msi installer. This enables admins to have single executable type installer and simplify installation process for admins.
n/a
1. Run: [Install Windows Agent](https://github.com/TheJumpCloud/support/blob/SA-3208-Windows-Agent-Installer-MSI/scripts/windows/InstallWindowsAgent.ps1) on a machine without JC Agent. Validate that the agent is installed silently and no changes in functionality.
2. Run: [Fix Windows Agent](https://github.com/TheJumpCloud/support/blob/SA-3208-Windows-Agent-Installer-MSI/scripts/windows/FixWindowsAgent.ps1 ) on a machine with JC Agent. Validate that the agent is uninstalled and installed silently and no changes in functionality.
[SA-3208]: …

Fix and install agents edit to MSI

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Private/Get-WebJCUser.ps1

* [SA-3282](https://jumpcloud.atlassian.net/browse/SA-3282) - localUserAccount field check
Previously, if a user had their localUserAccount field changed in the console, it would not be taken into account when the certs are generated which could lead to issues installing the script.
We simply added a conditional check to see if the `systemUsername` field (which corresponds with the `localUserAccount` field in the console) is not empty. If it is empty, we will continue to use the user's JumpCloud `username`. If it is not empty, we will instead use the user's `systemUsername` and set that as the user's `username` in a customObject that is returned in the `Generate-UserCert.ps1` function
No
1. Change a user's localUserAccount is the console
2. Assign the user to a device
3. Add the user to …

SA-3282: localUserAccount field check

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3322](https://jumpcloud.atlassian.net/browse/SA-3322) - Radius Cert Secret Fix
Fixed an issue with the `$JCUSERCERTPASS` not being correctly passed into Windows device commands when changed from default in `config.ps1`
N/A
1. Change the default value of `$JCUSERCERTPASS` in `config.ps1`
2. Generate and Distribute certs
3. Validate in the command that the Password value is as expected
4. Ensure that certificates are installed correctly
1. Change the password value in the JC Command to a random value and rerun command
2. Should produce an error stating the password does not match
N/A
[SA-3322]: https://jumpcloud.atlassian.net/browse/SA-3322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SA-3322: Radius Cert Secret Fix

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Functions/Private/Get-CommandObjectTable.ps1
scripts/automation/Radius/Functions/Private/Invoke-CommandsRetry.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3170](https://jumpcloud.atlassian.net/browse/SA-3170) - Replace Get-JCCommandResults with Search-JCSdkCommandResult
* [SA-3345](https://jumpcloud.atlassian.net/browse/SA-3345) - PFX Permission adjustment on MacOS distribute script
This change will reduce the time it takes to aggregate command results in tenants with large amounts of existing command results. The search endpoint doesn't require as many API calls to paginate the data.
Added chmod to the MacOS distribute script due to reports of permission issues on deployment
The command result clean up had to be adjusted to account for the new return body that the SDK uses compared to the Get-JCCommandResult function.
Attempt the deployment scripts as usual
View the command results by selection option 4 in the main menu
When viewing …

SA-3170: Replace Get-JCCommandResults with Search-JCSdkCommandResult

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3355](https://jumpcloud.atlassian.net/browse/SA-3355) - Throw exit 4 when no users are logged in to a windows host
Instead of throwing a generic exit 1, the radius example scripts will now throw an exit code 4 and inform users that no one is logged in.
On a windows host, deploy the radius cert with no user logged in. The exit code for the command result should be exit code 4.
When the correct user is logged in (previous behavior unchanged)
When the incorrect user is logged in (previous behavior unchanged)
When no one is logged in (new behavior)
[SA-3355]: https://jumpcloud.atlassian.net/browse/SA-3355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

no users logged in / changelog updates

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3379](https://jumpcloud.atlassian.net/browse/SA-3379) - Radius Cert Deployment, SSID mac set preference regardless of the certificate identifier type.
In previous iterations of the Radius Cert Deployment scripts, if a cert type of `EmailSAN` or `EmailDN` was selected and distributed to a macOS system, the step to assign a network SSID to the installed certificate would fail. The deployment script was erroneously attempting to identify a certificate by it's email identifier which is not a valid option for the [Security Set-Identity-Preference](https://ss64.com/osx/security-id.html) command. This would result in the command results throwing an exit code 2, and an "illegal option --e" error:
To address this, instead of identifying commands by their common name, or email (depending on …

v1.0.4, update distribute script

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Generic DMG Installer.md

* [SA-3359](https://jumpcloud.atlassian.net/browse/<jira-id>) - SA-3359
Update mac generic dmg installer to fix error issues.
n/a
Test with with a direct download link stored in S3 or links you're able to directly download from a website.
[SA-3359]: https://jumpcloud.atlassian.net/browse/SA-3359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update mac - generic dmg installer

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Private/Get-WebJCUser.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1
scripts/automation/Radius/Functions/Public/Generate-UserCerts.ps1

* [SA-3225](https://jumpcloud.atlassian.net/browse/SA-3225) - Local Username Certificate CN Fix
Previously when generating certificates with users who also have a systemUsername (local username account field set). The resulting certificates were generated with a users 'systemUsername'. Radius authentication only matches a user's username and user's with these certificates would never be allowed to access a radius backed network. 
This change tracks a user's localUsername and username (if both exist). Certs are generated with the users username but installed to the localUsername directory.
- Associate a user who has a systemUsername (local username account field set) to a radius access group
- Generate a radius user certificate for this user
- distribute the radius certificate to the …

local user fix for cert CN identification

---

PowerShell/JumpCloud Module/Public/Groups/SystemGroups/Remove-JCSystemGroup.ps1
PowerShell/JumpCloud Module/Public/Groups/UserGroups/Remove-JCUserGroup.ps1
PowerShell/JumpCloud Module/Tests/Public/Groups/SystemGroups/Remove-JCSystemGroup.tests.ps1
PowerShell/JumpCloud Module/Tests/Public/Groups/UserGroups/Remove-JCUserGroup.tests.ps1
PowerShell/ModuleChangelog.md

* [SA-3583](https://jumpcloud.atlassian.net/browse/SA-3583) - Remove-JCuserGroup/JCSystemGroup updates and bugfix
Addresses an issue with Remove-JCUserGroup and Remove-JCSystemGroup where the group names could not be identified. Groups can now be removed by id
Before pulling this version of the module, try to replicate the issue on 1.7.0 version of the module. Create a user or system group and attempt to remove it by name. The lookup never works and the group can not be deleted. 
Pull the contents of this branch, import and run:
```
New-JCUserGroup -GroupName Test1234
Remove-JCUserGroup -GroupName Test1234
New-JCSystemGroup -GroupName Test1234
Remove-JCSystemGroup - GroupName Test1234
```
The groups should be removed by name. They can also be removed by ID. 
[SA-3583]: …

2.8.0 changes to remove sys/usr groups

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3558](https://jumpcloud.atlassian.net/browse/SA-3558) - Multiple SSIDs with spaces
In previous versions of the radius example scripts, multiple SSIDs could be specified as long as those SSIDs did not have a space in the name. Some SSID set like "network_5G network_2.5G" would have been valid in a previous release whereas "network 5G network 2.5G" would not. In this release, space is no longer a delimiter to split network names, instead, the semicolon ";" is used to split network names. In this release setting the `$NETWORKSSID` variable to "network 5G;network 2.5G" would assign a macOS user's wifi certificate to both networks `network 5G` and `network 2.5G`
In addition this release changes the import certificate macOS security commands slightly by adding the `-x` flag which prevents …

1.0.6 multi ssid and non-exportable macos certs

---

.github/workflows/release-workflow.yml

* [SA-3608](https://jumpcloud.atlassian.net/browse/<jira-id>) - Set env variable casing for release nupkg step
Environment variables are case sensitive, this change reverts a change I made which inadvertently broke deployments.
[SA-3608]: https://jumpcloud.atlassian.net/browse/SA-3608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix env variable casing

---

PowerShell/JumpCloud Module/Public/Policies/PolicyTargets/Get-JCPolicyTargetGroup.ps1
PowerShell/ModuleChangelog.md

* [SA-3674](https://jumpcloud.atlassian.net/browse/SA-3674) -SA-3674-PolicyTargetGrouo-IndexError-Bug
Indexing error bug when policy group is not bound to a device group
n/a
1.  Run: `Get-JCPolicy | Get-JCPolicyTargetGroup`  with the current module version, it should return errors.
2. Import this module
3. Validate that the bug is fixed
[SA-3674]: https://jumpcloud.atlassian.net/browse/SA-3674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Get-JCPolicyTargetGroup Index Error Bug Fix

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3724](https://jumpcloud.atlassian.net/browse/SA-3724) - Radius Cert Util: Match case-insensitive macOS usernames
In macOS, it's possible for a user to define their username as `user1234` or `USER1234`. When JumpCloud takes of a user it'll perform a case insensive string comparison and take over the account that matches the username from JumpCloud.
Commands executed by JumpCloud in macOS run as shell scripts `/bin/bash` by default, this shell does not perform case-insensitive string comparisons. This patch version of the Radius Certificate Utility addresses this limitation by explicitly changing the `bash` match patterns to be case-insensitive.
N/A
- On a macOS device, create a user, define the username "USER1234"
- Within JumpCloud, create a user, define the username "user1234"
- …

SA-3724 Radius Certificate Utility - Match case-insensitive macOS usernames

---

PowerShell/Deploy/Build-Module.ps1
PowerShell/Deploy/Build-PesterTestFiles.ps1
PowerShell/Deploy/SdkSync/jcapiToSupportSync.ps1

* [SA-3705-Build-Module-Function](https://jumpcloud.atlassian.net/browse/SA-3705) - SA-3705-Build-Module-Function
This tool fixes the issue with the change from CircleCI to GHA migration where we are unable to write back our automations with building module, help and test files, and changelog edits. This process is now done locally with this change.
N/A
1. Run `."PowerShell/Deploy/Build-Module.ps1" -releasetype major `  
- Test out different release type
2. Validate changelog changes
- Change current version date to different date
- Rerun Build-Module
- Validate that the date is today's date 
3. Validate JumpCloud.psd1 changes (date, version)

Build Module Helpfiles, Pestertestfiles, and Changelog versioning tool

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Public/Distribute-UserCerts.ps1

* [SA-3732](https://jumpcloud.atlassian.net/browse/SA-3732) - Certificate Filter/ Similar Usernames
https://github.com/TheJumpCloud/support/issues/550
N/A
1. Have 2 users (john and john.smith)
2. Deploy certs to both users
3. Ensure that the command for each user only has their respective cert
[SA-3732]: https://jumpcloud.atlassian.net/browse/SA-3732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SA-3732: Certificate Filter/ Similar Usernames

---

.github/CODEOWNERS
.github/scripts/requirements.txt

* [CUT-3812](https://jumpcloud.atlassian.net/browse/CUT-3812) - GitPython Verison 
[Addresses Dependabot warning on gitpython verison](https://github.com/TheJumpCloud/support/security/dependabot/3)
Update CodeOwners file
Install requirements 
`pip3 install -r requirements.txt`
Run `python3 ./build_commands_gallery.py`
The script should update `commands.json` when a change is detected in commands gallery scripts
[CUT-3812]: https://jumpcloud.atlassian.net/browse/CUT-3812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

codeowners & gitpython version

---

scripts/automation/Radius/Config.ps1
scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
scripts/automation/Radius/Functions/Private/CertGeneration/Invoke-UserCertProcess.ps1
scripts/automation/Radius/Tests/Public/Start-DeployUserCerts.Tests.ps1

* [SA-3832](https://jumpcloud.atlassian.net/browse/SA-3832) - Cert Generation SN in Commands
Changes in #553  modified the command generation process. The Serial Number variable was no longer being passed into the generated command and, certificate installations would fail on devices. This addresses the issue by passing in the serial number when generating commands.
Additional tests were written to:
- Validate a certificate serial number is correctly passed into generated macOS/ Windows commands
- When changing certificate generation types
- - The subject headers of the certificate are correct
- - Any old .crt file is deleted for a user. i.e. users should not have more than one .crt file at any given time if the certificate generation type is changed from `usernameCN` to `emailSAN` 
No …

Cert Generation Tests + SN in Commands

---

CONTRIBUTING.md
README.md

* [CUT-3894](https://jumpcloud.atlassian.net/browse/CUT-3894) - Contributing documentation
Document required labels for `Command Gallery` and `JumpCloud PowerShell Module` pull requests.
Adds Contributing file for future documentation.
[CUT-3894]: https://jumpcloud.atlassian.net/browse/CUT-3894?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Readme and contributing documentation

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Generic DMG Installer.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install FireFox DMG.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install Microsoft Office.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install Slack DMG.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/LaunchDaemons/Mac - List All Launch Daemons.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/LaunchDaemons/Mac - Remove Daily System Restart Daemon.md
PowerShell/JumpCloud Commands Gallery/Mac Commands/LaunchDaemons/Mac - Schedule Daily System Restart Daemon.md

* [CUT-3969](https://jumpcloud.atlassian.net/browse/CUT-3969) - Replace Git.IO links
`Import-JCCommand` will no longer import git.io links, these remaining commands needed to have their url updated to the full path before these commands could be imported using `Import-JCCommand`
[CUT-3969]: https://jumpcloud.atlassian.net/browse/CUT-3969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

replace git.io links in command gallery

---

scripts/macos/log_collection.sh
scripts/windows/log_collection.ps1
scripts/windows/remove_windowsMDM.ps1

* [CUT-4185](https://jumpcloud.atlassian.net/browse/CUT-4185) - CUT-4185-WindowsMacOS log collection for troubleshooting
Allow customers to gather all necessary log files at once through Commands (Mac, Windows)
n/a
From JC Command:
1. Run mac script to a mac device
2. Validate all necessary log files are in the zip file: /Users/Shared/JumpCloudLogArchive-Timestamp.tar.gz
[CUT-4185]: https://jumpcloud.atlassian.net/browse/CUT-4185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Cut 4185 mac windows log collection

---

scripts/macos/log_collection.sh

* SUP-1448 https://jumpcloud.atlassian.net/browse/SUP-1448  Add "install.log*" to collected logs
Script was missing an installation log that is commonly useful for review
nope - just copied files to an already existing collection directory
Send via JC Command to macOS, set the automation variable to "true" and view results.

Added "install.log*" to collected assets.

---

scripts/windows/InstallWindowsAgent.ps1

* [UN-2389](https://jumpcloud.atlassian.net/browse/UN-2389) - Updating install script.
There is no need to check if JumpCloud is already installed,  we can just install over it.
The MSIEXEC command was wrong.
Removed unused variable.
[UN-2389]: https://jumpcloud.atlassian.net/browse/UN-2389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update windows install script

---

PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Forget RADIUS WiFi Network.md
PowerShell/JumpCloud Commands Gallery/commands.json

* [CUT-4344](https://jumpcloud.atlassian.net/browse/CUT-4344) - Forget WiFi Network Command
Creates a new Command template that should resolve the issue for customers using Radius and a user changes their password after connecting to a network and being unable to reconnect.
Testing involves having RADIUS configured
1. Have a RADIUS configuration enabled in your test tenant
2. Have a user assigned to a device connect to the RADIUS network
3. Change the user's password and attempt to reconnect (should not work)
4. Distribute this command to the affected device
5. Ensure that the command distributed correctly
i. Command results should not indicate a failure
ii. Validate that the scheduled task has been created via the task scheduler GUI and validate the PowerShell script exists in C:\scripts …

CUT-4344: Forget WiFi Network Command

---

scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
scripts/automation/Radius/Functions/Private/Commands/Get-CommandByUsername.ps1
scripts/automation/Radius/Functions/Public/Start-DeployUserCerts.ps1
scripts/automation/Radius/JumpCloud-Radius.psm1
scripts/automation/Radius/Tests/Public/Get-JCRGlobalVars.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-DeployUserCerts.Tests.ps1
scripts/automation/Radius/Tests/SetupRadiusOrg.ps1

* [CUT-4309](https://jumpcloud.atlassian.net/browse/CUT-4309) - Update Deploy-UserCertificate Functions to generate certs on SHA match
This release aims to reduce the amount of time required to generate and deploy certificates for users. In previous iterations of this script, the tool would generate a new command each time the script was run for each user. This version changes the command "trigger" to the SHA1 hash of a user's certificate and compares that value when running Start-DeployUserCerts.
This release also introduces a multi-threaded operation when the tool generates commands for "new" or "all" users in the radiusMembers list. 
Functionality for the changes should be already covered in our Pester tests for this module. To validate the changes in this pull request. Pull the …

Update Deploy-UserCertificate Functions to generate certs on SHA match

---

scripts/linux/log_collection.sh

* [SUP-1457](https://jumpcloud.atlassian.net/browse/SUP-1457) - Linux Log Collection Scripts
First iteration of the JumpCloud Log Collection Script for Linux systems. 
Nope - annoying due to number of distributions, but nothing is binary specific, and approach to collection was made to be as distribution agnostic as possible, a'la:
- List all possible log files across all supported distributions
- test if specific file exists
- collect if it does
Recommend testing on a Debian and RHEL based distro. Nothing is architecture specific, so only changes are due to file locations.
- set automate to true
- send as JC Command to managed Linux system
- collect generated log archive from /var/tmp/
- decompress and review logs on macOS & Windows systems to ensure readability.
[SUP-1457]: …

Linux JumpCloud Log Collection script

---

scripts/windows/UninstallWindowsAgent.ps1

* Changes to uninstall windows script in order to remove more pieces left behind. 
It first tries to run the original uninstaller in order to achieve the best clean up.  If these fails, work continues and code is forcibly removed.
Install agent, agent-app, remove assist, and or tray app.  Run uninstall script and assert windows "run" startup registry keys are removed, agent-app and remote assist are removed.  Also verify Jumpcloud* files in system32 are removed.

Update to windows uninstall script

---

PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install Chrome DMG.md

Update to universal dmg to ensure current stable version is installed.
* [SJ-9486](https://jumpcloud.atlassian.net/browse/SJ-9486)
Updates download URL to latest stable universal version. Old URL does not appear to be maintained (was pointing to a ~4 year old build)
[SJ-9486]: https://jumpcloud.atlassian.net/browse/SJ-9486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Mac - Install Chrome DMG.md

---

PowerShell/JumpCloud Module/Tests/Public/Utilities/CSV_Import/New-JCDeviceUpdateTemplate.Test.ps1
PowerShell/JumpCloud Module/Tests/Public/Utilities/CSV_Import/Update-JCDeviceFromCSV.Tests.ps1

* [CUT-4395](https://jumpcloud.atlassian.net/browse/CUT-4395) - Update-JCDeviceFromCSV Tests
Creates basic Pester suite for the two new functions for updating devices via CSV
- New-JCDeviceUpdateTemplate
- Update-JCDeviceFromCSV
The tests themselves are not every verbose as there is not much to the functions in their current state
Run the Pester tests for each of the functions
[CUT-4395]: https://jumpcloud.atlassian.net/browse/CUT-4395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update-JCDeviceFromCSV Tests

---

scripts/automation/Radius/Functions/Private/Reports/Get-LatestUserToDeviceReport.ps1
scripts/automation/Radius/Functions/Private/Reports/Get-ReportByID.ps1
scripts/automation/Radius/Functions/Public/Get-JCRGlobalVars.ps1

* [CUT-4519](https://jumpcloud.atlassian.net/browse/CUT-4519) - Get User to Device Reports with SDK Functions
- This change removes some of the invoke web request calls that were used previously to get the user to device reports.
- The `Get-JCRGlobalVars` function will now attempt to pull the latest user to device report if it's less than 10 minutes old. If the function is called and a report has been generated within 10 minutes, that report will be used to source user and system association data.
[CUT-4519]: https://jumpcloud.atlassian.net/browse/CUT-4519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Get User to Device Reports with SDK Functions

---

scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
scripts/automation/Radius/Functions/Private/CertDeployment/Get-CertInfo.ps1
scripts/automation/Radius/Functions/Private/CertDeployment/Get-ExpiringCertInfo.ps1
scripts/automation/Radius/Functions/Private/Commands/Invoke-CommandsRetry.ps1
scripts/automation/Radius/Functions/Private/Menus/Show-GenerationMenu.ps1
scripts/automation/Radius/Functions/Private/Settings/New-JCRSettingsFile.ps1
scripts/automation/Radius/Functions/Public/Get-JCRGlobalVars.ps1

* [CUT-4551](https://jumpcloud.atlassian.net/browse/CUT-4551) - Use Universal Time to Compare Certificates
When running the radius certificate tool on devices with various datetime cultures where datetimes are stored as dd/mm/yyyy, the previous version of the tool would fail to compare expiring certificate dates. This update converts all stored dates to universal date time.
[CUT-4551]: https://jumpcloud.atlassian.net/browse/CUT-4551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use Universal Time to Compare Certificates

---

scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
scripts/automation/Radius/Functions/Private/UserTable/Set-UserTable.ps1
scripts/automation/Radius/Functions/Public/Get-JCRGlobalVars.ps1
scripts/automation/Radius/Tests/Public/Start-GenerateUserCerts.Tests.ps1

* [CUT-3740](https://jumpcloud.atlassian.net/browse/CUT-3740) - Radius Single User Array Fix
Fixes an issue that causes non-terminating errors when a single user is in the UserGroup for a Radius deployment
This was caused by the function not recognizing the single user as an array, causing some indexing errors. This is fixed by manually casting the object to an array.
N/A
1. Assign 1 user to your Radius UserGroup
2. Attempt to generate a userCert for that user
[CUT-3740]: https://jumpcloud.atlassian.net/browse/CUT-3740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CUT-3740: Radius Single User Array Fix

---

scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Functions/Private/Menus/Get-ResponsePrompt.ps1
scripts/automation/Radius/Functions/Public/Start-GenerateRootCert.ps1
scripts/automation/Radius/Functions/Public/Start-GenerateUserCerts.ps1

* [CUT-4091](https://jumpcloud.atlassian.net/browse/CUT-4091) - CUT-4091-VerifyRootCertKeyPassword
- Ensures that the inputted root cert password is validated by having it re-entered
- Bug fix: 'E' exit not working properly for Generate Root and User cert menus
n/a
**Root Cert Password Validation**
1. Generate a root cert using the GUI
2. Validate that you have to enter the password twice
- Validate that it fails if you enter two different passwords
- Entering the same password on both prompts should be a success
**Bug Fix**
1. Go to generate root cert menu GUI then enter `E`, this should take you to main menu
2. Go to generate user cert menu GUI then enter `E`, this should take you to main menu
[CUT-4091]: https://jumpcloud.atlassian.net/browse/CUT-4091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …

Cut 4091 verify password for cert key

---

scripts/macos/log_collection.sh

* [SUP-1496](https://jumpcloud.atlassian.net/browse/SUP-1496) - macOS - missed PWM log location
Collects previously missed logs for JumpCloud Password Manager daemon which are buried in ~/Library/Application Support/...
nope
Run VM, bind to JC, Install PWM and add item to ensure logs are populated. Run collection script and look for entries within the archive located in [archive root]/userLogs/[username]/PWM_daemon_logs
[SUP-1496]: https://jumpcloud.atlassian.net/browse/SUP-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added PWM daemon log collection

---

.gitignore
scripts/automation/Radius/Changelog.md
scripts/automation/Radius/Functions/Private/Menus/Get-ResponsePrompt.ps1
scripts/automation/Radius/Functions/Private/Menus/Show-RadiusMainMenu.ps1
scripts/automation/Radius/Functions/Private/Menus/Show-RootCAGenerationMenu.ps1
scripts/automation/Radius/Functions/Public/Start-GenerateRootCert.ps1
scripts/automation/Radius/JumpCloud-Radius.psm1
scripts/automation/Radius/Tests/Public/Get-JCRGlobalVars.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-DeployUserCerts.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-GenerateRootCert.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-GenerateUserCerts.Tests.ps1
scripts/automation/Radius/readme.md

* [CUT-4092](https://jumpcloud.atlassian.net/browse/CUT-4092) - Generate-RootCert-Menu
Adds new functionality when generating/updating root certificate. 
Root Cert Menu system with 3 options:
1.  `New` - This will generate a new root certificate. If a root certificate is present, it will be an option to overwrite it
2.  `Replace` - Will replace current root cert and the generated root cert will have a different serial number. User certs generated with the previous root cert `will no longer authenticate`
3. `Renew` - Renewing will replace the current root cert but will retain the same serial number and headers. User certs generated with the previous root cert `will continue to authenticate`
N/a
**Generate new root cert**
Note: Make sure to empty the cert folder before running new root cert …

root cert menu

---

scripts/automation/Radius/Functions/Private/CertDeployment/Get-CertInfo.ps1
scripts/automation/Radius/Functions/Private/HashFunctions/Test-UserFromHash.ps1
scripts/automation/Radius/Tests/Public/Get-JCRGlobalVars.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-GenerateRootCert.Tests.ps1
scripts/automation/Radius/Tests/Public/Start-GenerateUserCerts.Tests.ps1

* [CUT-4093](https://jumpcloud.atlassian.net/browse/CUT-4093) - Validate membership tests
- If large numbers of certificates are stored in the user certificates directory this update to the module will parse only the certificates that match usernames of the users in the defined radius group.
- BugFix for cases where a user was in the radius member group but their cert could not be identified if they were the first user in the group.
- Update tests to expand expected behavior
Automated tests cover these changes
[CUT-4093]: https://jumpcloud.atlassian.net/browse/CUT-4093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Tests for radius membership

---

scripts/automation/Radius/Functions/Public/Get-JCRCertReport.ps1
scripts/automation/Radius/JumpCloud-Radius.psd1
scripts/automation/Radius/Tests/Public/Get-JCRCertReport.Tests.ps1

* [CUT-4602](https://jumpcloud.atlassian.net/browse/CUT-4602) - Multi-Group Radius Report Function
Created a new function to generate a report that accepts multiple groupIDs and will output a report that contains the following properties:
username
userid
systemHostname
systemID
systemOS
CertSerialNumber
CertExpirationDate
CertInstalled
The function will need to be added to the end of the [MultiGroup RADIUS script](https://gist.github.com/jworkmanjc/d5a3f26c6c77aec15ed4af51a313a219) in order to function correctly
1. Import the RADIUS module
a. NOTE: You may have to force update the global variables to ensure that the hashes are populated, it is also recommended to have at least a few certs deployed
2. Run the following function: 
```powershell
Get-JCRCertReport -UserGroupIDs "usergroupid1" …
```

CUT-4602: Multi-Group Radius Report Function

---

scripts/macos/remove_mac_agent.sh

* [AR-741](https://jumpcloud.atlassian.net/browse/AR-741) - MacOS remove agent script sync with removeAgent script
Make sure the agent and all agent components are cleanly removed from the device
No
Run the script on a JumpCloud managed device with mangaged users and make sure ather the script is run the device is no longer managed by JumpCloud and the managed users are now local users of the device and can log in.
[AR-741]: https://jumpcloud.atlassian.net/browse/AR-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AR-741 MacOS remove agent script sync with removeAgent script

---

scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
scripts/automation/Radius/Tests/Public/Start-DeployUserCerts.Tests.ps1

* [CUT-4540](https://jumpcloud.atlassian.net/browse/CUT-4540) - Users.json command names are not being recorded correctly
This issue resolves an issue with the generated command names being recorded incorrectly in the users.json data file. The commandIDs were still being recorded correctly, but the command names were not being updated to match the predetermined naming structure.
No, there are automated tests in place to validate that the command names are set correctly.
[CUT-4540]: https://jumpcloud.atlassian.net/browse/CUT-4540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

users.json command names are not being recorded correctly

---

scripts/macos/log_collection.sh

On some macOS devices, the user's home directory path differs from their username. This discrepancy caused log collection failures, as the script incorrectly assumed the home directory was directly derived from the username.
This commit resolves the issue by using `dscl` to accurately retrieve the home directory path for both standard and managed users, ensuring reliable log collection regardless of home directory configuration.
n/a
use the log collection script on a device with a user having a homedir different than the username:
for example in users & groups:
- user name = ludovic
- home directory = /Users/ludovic_dir
In this screenshot, the username is ludovic, however the home directorty is /Users/ludovic_dir instead of the standard /Users/ludovic dirrectory:

Update log_collection.sh - Correct Home Directory Retrieval for Log Collection

---

scripts/linux/log_collection.sh

* [SUP-1503] (https://jumpcloud.atlassian.net/browse/SUP-1503) - SUP-1503
Improves the capturing of managed usernames during log collection.
The current expression does not handle if a username has a period or such -  For example:
Currently, if a username was set as:
`terry.test`
It would only capture:
`terry`
N/A
Run the Linux log collection script on a device that has various usernames and confirm they are printed correctly to the managerUsers file in the log collection:
`jumpcloudInfo > managedUsers.txt`
**Current expression output:**
**Updated expression output:**
[SUP-1503]: https://jumpcloud.atlassian.net/browse/SUP-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updated regular expression for improved collection of managed usernames

---

scripts/macos/log_collection.sh

* [SUP-1514](https://jumpcloud.atlassian.net/browse/SUP-1514) - Device Trust Certificate capture update
Currently, the function for listing / capturing Device Trust Cert within the script will only capture if and for the currently logged-in user on the device - Though in most cases this will typically not be an issue, if the log collection is run and a non-managed user is logged in, the cert info wouldn’t be checked for any possible managed users on the device, possibly then returning a false negative.
This change is to move the current logic for capturing the device cert info into the FOR loop against managed users.
N/A
Run the script from JC commands with no user logged in and confirm the Device Cert info and file are written for the managed users on the device.
[SUP-1514]: …

SUP-1514: Amended Device Cert capture

---

scripts/linux/log_collection.sh

* [SUP-1506](https://jumpcloud.atlassian.net/browse/SUP-1506) - Linux - Log Collection Logging
Integrate a logging function into the log collection so that any terminal or stdout is also written to a log file, which will then be included in the log collection archive.
This will prevent admins from needing to potentially send a copy of the terminal output along with the log collection. 
Implementing this now can be beneficial for future iterations of the script.
Further to this, Added the checking and capturing JumpCloud Device Certificate details. 
Also include the addition of listing running JumpCloud services & processes on the device.
These additions will bring the Linux log collection in line with matching behaviour to our macOS log collection script.
N/A
Run log collection script …

SUP-1506: Linux - Log Collection Logging

---

scripts/macos/log_collection.sh

* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>
This collects .ips and diagnostic files related to Apple's Certificate Service, which is believed to be crashing & related to the current MDM unenrollment issues. 
nope
create a file in /Library/Logs/DiagnosticReports/CertificateService-2025-06-20-085424.ips (this mimics Apple's naming convention for the files) and run the script. 
Run the script via JumpCloud Commands (setting automate=true)
Verify the inclusion of the "DiagnosticReports/<filename>" in the log archive.

Added logic to collect diagnostic information for CertificateService
