- PowerShell/JumpCloud.psd1
> Updated data in PowerShell manifest

- PowerShell/JumpCloud.psd1
- PowerShell/JumpCloud.psm1
- PowerShell/en-Us/JumpCloud-help.xml
- PowerShell/en-Us/about_JumpCloud.help.txt
- PowerShell/test/ImportExample_Pester_Tests_1.1.0.csv
- PowerShell/test/JumpCloud.1.0.0.Tests.ps1
- PowerShell/test/JumpCloud.1.1.0.Tests.ps1
See changes in [CHANGELOG.md](https://github.com/TheJumpCloud/support/blob/master/PowerShell/CHANGELOG.md)
> PowerShell module version 1.1

- PowerShell/JumpCloud.psd1
- PowerShell/JumpCloud.psm1
- PowerShell/en-Us/JumpCloud-help.xml
- PowerShell/en-Us/about_JumpCloud.help.txt
- PowerShell/test/JumpCloud.1.0.0.Tests.ps1
- PowerShell/test/JumpCloud.1.1.0.Tests.ps1
- PowerShell/test/JumpCloud.1.2.0.Tests.ps1
> Power shell module

- PowerShell/JumpCloud.psm1
Fixed bug for New-JCCommandFromURL
> Fixed New-JCCommandFromURL

- PowerShell/JumpCloud.psd1
- PowerShell/JumpCloud.psm1
- PowerShell/en-Us/JumpCloud-help.xml
- PowerShell/en-Us/about_JumpCloud.help.txt
- PowerShell/test/JumpCoud.1.4.0.Tests.ps1
Updated for admins with a need for speed.
> 1.4 release

- PowerShell/JumpCloud.Office365.SSO/JumpCloud.Office365.SSO.psd1
- PowerShell/JumpCloud.Office365.SSO/Private/HelperFunctions/Test-MSOnline.ps1
- PowerShell/JumpCloud.Office365.SSO/Public/Disable-JumpCloud.Office365.SSO.ps1
- PowerShell/JumpCloud.Office365.SSO/Public/Enable-JumpCloud.Office365.SSO.ps1
- PowerShell/JumpCloud.Office365.SSO/Public/Show-JumpCloud.Office365.SSO.ps1
> Module 0.9.0

- scripts/macos/remove_mac_agent.sh
Fixes https://github.com/TheJumpCloud/jumpcloud-issues/issues/3677
It's all in the title!
> Update Mac Agent Uninstall script to delete Service Account if present

- api-utils/JumpCloud_API_Go_Examples/DedupeSystemUsersUnixUidGuid/README.md
Updates the readme to make it more clear on how to setup and run the script.
> Updated readme with cleaner install instructions

- PowerShell/JumpCloud Module/Private/NestedFunctions/Invoke-JCApiGet.ps1
- PowerShell/JumpCloud Module/Public/Policies/PolicyTargets/Get-JCPolicyTargetGroup.ps1
- PowerShell/JumpCloud Module/Public/Policies/PolicyTargets/Get-JCPolicyTargetSystem.ps1
Remvoing broken/extra Policy exists validation.
> Bug-JCPolicy

- scripts/windows/AD_migration_toolkit/SystemMigration.ps1
Adds validation for agent install and increases restart count down timer to 10 seconds
> Ad migration windows scripts

- PowerShell/JumpCloud Module/Public/Users/New-JCUser.ps1
- PowerShell/JumpCloud Module/Public/Users/Set-JCUser.ps1
- Removes validate set from enrollment days and moves this validate to the API.
- Resolves issue with tab complete for dynamic parameter 'enrollments'
- Adds value by pipeline input to all parameters in Set-JCUser
> creating branch

- PowerShell/JumpCloud Module/Public/Authentication/Connect-JCOnline.ps1
- PowerShell/JumpCloud Module/Public/Commands/New-JCDeploymentTemplate.ps1
- PowerShell/JumpCloud Module/Public/Utilities/CSV_Import/Import-JCUsersFromCSV.ps1
- PowerShell/JumpCloud Module/Public/Utilities/CSV_Import/New-JCImportTemplate.ps1
- PowerShell/JumpCloud Module/Public/Utilities/CSV_Import/Update-JCUsersFromCSV.ps1
- PowerShell/JumpCloud Module/Public/Utilities/Get-JCBackup.ps1
- PowerShell/JumpCloud Module/Tests/HelperFunctions.ps1
- PowerShell/JumpCloud Module/Tests/InvokePester.ps1
> updated with logic for host terminals

- scripts/macos/remove_mac_agent.sh
Force /opt/jc/bin/removeAgent to be executable
> Force /opt/jc/bin/removeAgent to be executable

- PowerShell/JumpCloud Module/JumpCloud.psd1
- PowerShell/JumpCloud Module/Public/Authentication/Connect-JCOnline.ps1
- PowerShell/JumpCloud Module/Public/Users/Set-JCUser.ps1
- PowerShell/ModuleBanner.md
- PowerShell/ModuleChangelog.md
> Sr set jc user bugfix

- PowerShell/JumpCloud Module/Docs/Get-JCUser.md
- PowerShell/JumpCloud Module/Docs/Set-JCUser.md
- PowerShell/JumpCloud Module/Public/Users/Get-JCUser.ps1
- PowerShell/JumpCloud Module/Public/Users/Set-JCUser.ps1
- PowerShell/JumpCloud Module/Public/Utilities/CSV_Import/Update-JCUsersFromCSV.ps1
- PowerShell/JumpCloud Module/Tests/Public/Users/Get-JCUser.tests.ps1
- PowerShell/JumpCloud Module/Tests/Public/Users/Set-JCUser.tests.ps1
ADB add attributes external_dn and external_source_type
> Sa 455 sr adb attributes add

- PowerShell/JumpCloud Module/Private/NestedFunctions/Invoke-JCApi.ps1
Adding -UseBasicParsing parameter to the log message and Invoke-WebRequest command.
> #108 Removing IE dependency

- ADMU/ReadMe.md
* Updates hardcoded GH links and images to correct location
> ADMU v1.0.0 Readme fix

- scripts/windows/InstallWindowsAgent.ps1
> Sr install windows agent unattended

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Set Auto Logout Delay.md
This is a new command for setting auto logout
> new command

- PowerShell/JumpCloud Module/Public/Users/Set-JCUser.ps1
Some parameters were missing the ability to accept pipeline input
> Updating Set-JCUser

- PowerShell/JumpCloud Module/Public/Utilities/Get-JCBackup.ps1
Quick fix for Get-JCBackup. This function could use a refactor in the future.
> updating recursive logic of get-jcbakup

- scripts/macos/install_agent_and_serviceaccount.sh
- scripts/macos/verify_serviceaccount.sh
Silent install script and verify service account script needed bash headers.
> Add bash header

- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/README.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Install Google Chrome.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Install Mozilla Firefox.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Install Notepad++.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - List Packages Managed by Chocolatey.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Uninstall Google Chrome.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Uninstall Mozilla Firefox.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Uninstall Notepad++.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Choco - Update Packages Managed by Chocolatey.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Chocolatey/Windows - Install Chocolatey.md
Still working on the KB article, but I believe the Github pieces should be ready to merge into Master, once we have the KB done
> Sa 679 chocolatey

- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Run Once Template - Remove System From Associated System Group.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Run Once Template - Remove System From Command.md
Run once templates using API key
> Sr windows command run once templates

- scripts/windows/FixWindowsAgent.ps1
Added logic for silent install / uninstall to this script.
> Sa 755 update fix windows agent.ps1

- scripts/macos/install_agent_and_serviceaccount.sh
Allow the connect key via command line. This will allow for easier scripting/install
> add getopts logic for -k to allow connect key via command line

- PowerShell/ModuleBanner.md
Updated current banner with info about JumpCloud Dashboard PowerShell Module
> Dashboard notification

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install MDM Profile.md
Check if profile is installed and whether or not it's user approved MDM. If the profile is not installed, install the jumpcloud MDM profile and verify it's installed using the identifier com.jumpcloud.mdm
> check profile installed, verify id on install

- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Snap - Install Microsoft VS Code.md
- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Snap - Install Slack.md
- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Snap - Install Snap Daemon.md
- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Snap - Remove Slack.md
Several example Snap commands added to the Linux Command Gallery
> Sa 1250 snap commands

- PowerShell/JumpCloud Module/JumpCloud.psd1
- PowerShell/JumpCloud Module/JumpCloud.psm1
- PowerShell/ModuleBanner.md
- PowerShell/ModuleChangelog.md
Quick change to psm1 file to conditionally load the SSL profile in powershell 5.1
> Conditionally load ssl profile

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Application Installs/Mac - Install Microsoft Office.md
@joffems I'm opening your pull request on this branch and made a few changes to your script, once I get another set of eyes on this we'll approve. Thank you for contributing.
> Example to install Office 365 with Commands Gallery 

- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Set Agent Log Level to Debug.md
- PowerShell/JumpCloud Commands Gallery/Linux Commands/Linux - Set Agent Log Level to Default.md
- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Pull jcagent.log.md
- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Set Agent Log Level to Debug.md
- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Set Agent Log Level to Default.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Set Agent Log Level to Debug.md
- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Set Agent Log Level to Default.md
Publishes Windows, Mac & Linux commands to the command gallery to change the system agent logging level.
> SA-240 - Logging Level Commands

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Set Agent Log Level to Trace.md
Duplicate of the debug command but the variable has been updated and the name of the launch daemon
> Adding trace

- scripts/macos/agent_diagnostics.sh
In regards to [HE-1324](https://jumpcloud.atlassian.net/browse/HE-1324):
After updating agent_diagnostics.sh for HE-1324, I noticed that the support repo's copy of this file was out of date.
So, this PR is to bring it up to date.
> HE-1324: Updated agent_diagnostics.sh to match the latest version in the jumpcloud-agent repo.

- scripts/api/system_context/system_delete_self.sh
- scripts/api/system_context/system_post_systemgroup_add.sh
- scripts/api/system_context/system_post_systemgroup_remove.sh
- scripts/api/system_context/system_put_self.sh
- scripts/api/system_context/windows_examples/system_delete_self.ps1
- scripts/api/system_context/windows_examples/system_get_command_associations.ps1
- scripts/api/system_context/windows_examples/system_get_self.ps1
- scripts/api/system_context/windows_examples/system_get_systemGroup.ps1
- scripts/api/system_context/windows_examples/system_get_user_associations.ps1
- scripts/api/system_context/windows_examples/system_post_systemgroup_add.ps1
- scripts/api/system_context/windows_examples/system_post_systemgroup_remove.ps1
- scripts/api/system_context/windows_examples/system_put_self.ps1
Updated syntax for mac system context example scripts, added system context example scripts for windows hosts.
> Sa 1613 system context windows example

- scripts/api/v1/radius/dhcpRadiusUpdate.sh
Added 2 extra variables of "name" and "sharedSecret" to script to account for changes to v1 API made in Nov 2020
> added static fields to PUT

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Package Managment/Mac - Install AutoPkg Package Manager.md
Update install AutoPkg example to pull latest version of AutoPkg from GH release page
> install latest autopkg version

- .circleci/workflows.yml
* [sa-1770](https://jumpcloud.atlassian.net/browse/sa-1779) - Azure Devops to CircleCI Migration
Fix merge to master workflow.
> Jump cloud module 1.18.5

- _posts/2022-03-15-Policy-Report.md
- tag/policy.md
* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>
Give admins an option to create policy report
No
Run the script and follow the prompts. Test Mac, Linux, and Windows policies that is bound to systems.
> Sa 2422 policy report

- PowerShell/JumpCloud Module/Docs/Get-JCCommand.md
* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>
Just some tidying up of the docs for `Get-JCCommand`. I think someone copied a previous example and there was some information that wasn't relevant or correct for the given example. Tried to match the existing language where possible!
N/A
N/A
See diff
> Get-JCCommand docs update

- _posts/2022-08-04-Report-Commands-To-Systems-And-Groups.md
* [SA-2786](https://jumpcloud.atlassian.net/browse/SA-2786) - Command to system, system group report
Report on commands and bound systems/ groups
> command report

- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Install Remote Assist.md
* [TX-360](https://jumpcloud.atlassian.net/browse/TX-360) - Add command to install RAS for EA on Windows
> Add command to install RAS for EA on Windows

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Remote Assist.md
* [TX-359](https://jumpcloud.atlassian.net/browse/TX-359) - Add Command to install RAS for EA on Mac
> Add Command to install RAS for EA on Mac

- PowerShell/JumpCloud Commands Gallery/Windows Commands/Windows - Install Remote Assist.md
* [TX-357](https://jumpcloud.atlassian.net/browse/TX-357) - Update production URL
Points to the latest release, rather than pinning to a specific version
> Update production URL

- PowerShell/JumpCloud Commands Gallery/Mac Commands/Mac - Install Remote Assist.md
* [TX-396](https://jumpcloud.atlassian.net/browse/TX-396) - Use PKG not DMG
> TX-396 Use PKG not DMG [skip ci]

- scripts/windows/FixWindowsAgent.ps1
* [SA-2867](https://jumpcloud.atlassian.net/browse/SA-2867) - Replace outdated WMI commands
A few updates to the fix-windowsagent script. Replace Get-WMIObject with updated Get-CIMInstanct cmdlet.
> fix windows agent changes

- PowerShell/ModuleChangelog.md
* [SA-3607](https://jumpcloud.atlassian.net/browse/<jira-id>) - Update powershell module release + github action workflow for CI tests + release
[SA-3607]: https://jumpcloud.atlassian.net/browse/SA-3607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release PowerShell Module 2.8.0

- _posts/2022-02-10-Grant-Admin-Rights.md
* [CUT-3952](https://jumpcloud.atlassian.net/browse/CUT-3952) - Update documentation for granting admin rights
[CUT-3952]: https://jumpcloud.atlassian.net/browse/CUT-3952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> documentation update

- .github/workflows/radius-module-ci.yml
- scripts/automation/Radius/Extensions/extensions-emailSAN.cnf
- scripts/automation/Radius/Functions/Private/CertDeployment/Deploy-UserCertificate.ps1
- scripts/automation/Radius/Functions/Private/CertDeployment/Get-CertInfo.ps1
- scripts/automation/Radius/Functions/Private/CertGeneration/Generate-UserCert.ps1
- scripts/automation/Radius/Functions/Private/HashFunctions/Test-UserFromHash.ps1
- scripts/automation/Radius/Functions/Private/Settings/Update-JCRUsersJson.ps1
- scripts/automation/Radius/Functions/Public/Get-JCRGlobalVars.ps1
- scripts/automation/Radius/Functions/Public/Start-GenerateRootCert.ps1
- scripts/automation/Radius/JumpCloud-Radius.psm1
- scripts/automation/Radius/Start-RadiusDeployment.ps1
- scripts/automation/Radius/Tests/HelperFunctions.ps1
- scripts/automation/Radius/Tests/Invoke-Pester.ps1
- scripts/automation/Radius/Tests/ModuleValidation/ModuleVersion.Tests.ps1
- scripts/automation/Radius/Tests/Public/Get-JCRGlobalVars.Tests.ps1
- scripts/automation/Radius/Tests/Public/Start-DeployUserCerts.Tests.ps1
- scripts/automation/Radius/Tests/Public/Start-GenerateRootCert.Tests.ps1
- scripts/automation/Radius/Tests/Public/Start-GenerateUserCerts.Tests.ps1
- scripts/automation/Radius/Tests/SetupRadiusOrg.ps1
- scripts/automation/Radius/readme.md
* [CUT-3380](https://jumpcloud.atlassian.net/browse/CUT-3380) - Add Tests to Radius Module
Adds a series of pester tests to the radius user cert deployment module. 
[CUT-3380]: https://jumpcloud.atlassian.net/browse/CUT-3380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Cut 3380 radius ci cd

- _posts/2023-03-23-Rename-Local-Username.md
* [CUT-4135](https://jumpcloud.atlassian.net/browse/CUT-4135) - Update rename local user bulk script
Simplifies the scripts by just having customers upload the migrationUsers.CSV to the command for each Windows/macOS JumpCloud command. Updates the macOS script to restart after a minute instead of force closing the loginwindow — this worked in previous versions of macOS but seems to freeze the JumpCloud login window on login. 
[CUT-4135]: https://jumpcloud.atlassian.net/browse/CUT-4135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update rename local user bulk script

- scripts/macos/RenameMacUserNameAndHomeDirectory.sh
* [CUT-4138](https://jumpcloud.atlassian.net/browse/CUT-4138) - Update Rename Local Username macOS Scripts 
This change updates the series of commands issued to restart a device after changing a local username. Depending on how the script was run, the previous version might not execute correctly. This version of the script can be executed through a JumpCloud command. The command will finish and show an exit code of 0 assuming all other changes were successful. 
NA
- Create a macOS command in JumpCloud upload this script to the script file contents. 
- Setup a macOS device with some local account with an account name like `localUser`
-  set the command body to change the account name `localuser` to 'newlocaluser`
- Execute the command on that device with the `localUser` account.
- The …
> Update Rename Local Username macOS Scripts 

- scripts/windows/InstallWindowsAgent.ps1
Reverts TheJumpCloud/support#607
> Revert "Update windows install script"

- scripts/windows/log_collection.ps1
* [<jira-id>](https://jumpcloud.atlassian.net/browse/<jira-id>) - <jira-title>
Added check for PowerShell V5 or higher.
Updated GPResult command to run successfully via JC Commands
Updated reg and command syntax to correctly gather Active Directory registry keys
Added commands to gather and name the jc-user-agent.log and jcupdate.log from user folders.
Added command to grab the Windows Version.
Fixed the command to gather list of collected files.
Running via local PowerShell instance and via JC Commands.
N/A
> Added PS ver Check, added files, fixed the broke.

- .github/workflows/release-workflow.yml
Ubuntu runner's new update removed Nuget.
Add install step for nuget
> Fix nuget install dependency

- scripts/macos/install_agent_and_serviceaccount.sh
* [SJ-10166](https://jumpcloud.atlassian.net/browse/SJ-10166) - update install_agent_and_serviceaccount.sh script
JumpCloud now supports a new connect key format that is different from the previous 40-character format. This change supports both formats.
No
Uninstall agent on current device. 
Manually delete `/opt/jc/agentBootstrap.json` if still present. 
Run new installer w/ new connect key format.
Note: Install should be silent (should not prompt for connect key)
[SJ-10166]: https://jumpcloud.atlassian.net/browse/SJ-10166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update install script to support new connect key format

- scripts/automation/assign_primary_user.ps1
* [HY-3730](https://jumpcloud.atlassian.net/browse/HY-3730) - Assign Primary Users script failing for large org (4k devices)
Script was failing when processing systems for a larger org with ~4000 devices
N/A
This can be ran on an org with any number of devices. The org where this was failing already successfully ran this version of the script successfully
[HY-3730]: https://jumpcloud.atlassian.net/browse/HY-3730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HY-3730 Swapped Get-JCSystemUser with New-JCReport
